apiVersion: v1
kind: Secret
metadata:
  name: distributed-transactions-secrets
  namespace: distributed-transactions
type: Opaque
stringData:
  ORDER_DB_USERNAME: order_user
  ORDER_DB_PASSWORD: order_password

  BILLING_DB_USERNAME: billing_user
  BILLING_DB_PASSWORD: billing_password

  NOTIFICATION_DB_USERNAME: notification_user
  NOTIFICATION_DB_PASSWORD: notification_password

  INVENTORY_DB_USERNAME: inventory_user
  INVENTORY_DB_PASSWORD: inventory_password

  DELIVERY_DB_USERNAME: delivery_user
  DELIVERY_DB_PASSWORD: delivery_password

  JWT_SECRET: local-development-jwt-secret-change-me-123456789
