apiVersion: v1
kind: Secret
metadata:
  name: order-service-db-secret
type: Opaque
stringData:
  # Эти два ключа использует приложение.
  DB_USERNAME: order_user
  DB_PASSWORD: order_password

  # Эти два ключа использует Helm-чарт PostgreSQL.
  postgres-password: postgres_admin_password
  password: order_password