apiVersion: v1
kind: Secret
metadata:
  name: stream-processing-secrets
  namespace: stream-processing
type: Opaque
stringData:
  ORDER_DB_USERNAME: order_user
  ORDER_DB_PASSWORD: order_password

  BILLING_DB_USERNAME: billing_user
  BILLING_DB_PASSWORD: billing_password

  NOTIFICATION_DB_USERNAME: notification_user
  NOTIFICATION_DB_PASSWORD: notification_password

  JWT_SECRET: local-development-jwt-secret-change-me-123456789
